services:
  tg-bot:
    image: yt-bot
    network_mode: host
    build:
      context: .
    depends_on:
      - telegram-bot-api
      - bgutil-provider

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: ${API_ID}
      TELEGRAM_API_HASH: ${API_HASH}
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"
      
  bgutil-provider:
    image: brainicism/bgutil-ytdlp-pot-provider
    ports:
      - "4416:4416"


volumes:
  telegram-bot-api-data:
